version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
